name: Build and push - All

on:
  schedule:
    - cron: '0 8 * * *'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Base Image
      - name: Build and push 1.55.1
        uses: docker/build-push-action@v5
        with:
          context: ./1.55.1/.
          push: true
          tags: labordigital/playwright:1.55.1
          platforms: linux/amd64,linux/arm64
          file: ./1.55.1/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Base Image
      - name: Build and push 1.56.1
        uses: docker/build-push-action@v5
        with:
          context: ./1.56.1/.
          push: true
          tags: labordigital/playwright:1.56.1
          platforms: linux/amd64,linux/arm64
          file: ./1.56.1/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Base Image
      - name: Build and push 1.57.0
        uses: docker/build-push-action@v5
        with:
          context: ./1.57.0/.
          push: true
          tags: labordigital/playwright:1.57.0
          platforms: linux/amd64,linux/arm64
          file: ./1.57.0/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max